### ISSUE TITLE
Scrolling on iPad

### ISSUE THREAD

**Issue by milesmcclane** [Athou/commafeed#1168]
**Describe the bug**
Scrolling using a trackpad or scroll wheel on mouse doesn’t work

**To Reproduce**
Open commafeed on safari or by using the standalone web app whilst using iPadOS, scrolling the side bar or any element doesn’t work using a BT mouse wheel or the trackpad on a Magic Keyboard.

**Expected behavior**
I assume that this should work like other websites - fully trackpad enabled

- CommaFeed version (or "commafeed.com"): Latest commafeed.com
- Safari
- iPad Pro 12.9 M1

**Additional context**
Potentially its not an issue with Commafeed, rather an Apple thing, but most other websites function normally using pointing devices

**Comment by SConaway** [comment]
I'm having this issue too. The `overscroll-behavior: none` CSS property on `html, body` seems to be causing this issue. However, I can't reproduce it on a fresh install.

**Comment by zahidhanif** [comment]
Just spun up a docker instance and I am having the same problem on my iPad and MacBook using Safari. Weirdly the demo instance is not having this problem.

**Comment by SConaway** [comment]
Some updates now that I've had more time to play around with this: 

- This issue only seems to occur once the sidebar needs to be able to scroll—i.e. the subscription list is long. After adding lots of entries, I'm able to consistently reproduce this, but only in safari on Mac. 

- As a temporary workaround, I've added to the custom styles on Commafeed itself. 
```css
html, body {
    overscroll-behavior: unset;
}
```

- I'm testing some long-term changes and will create a PR soon with them.

**Comment by Athou** [comment]
I just deployed a new version on www.commafeed.com that keeps pull-to-refresh enabled for Safari, does that solve the issue?

**Comment by SConaway** [comment]
Everything seems to work for me, tested on
- iPhone Safari and Chrome
- iPad Safari and Chrome
- Macbook Safari and Firefox

**Comment by Athou** [comment]
Awesome, thanks! I'll close this issue then 👍

**Comment by SConaway** [comment]
I'm back..has the commit been pushed to Docker hub? Just pulled the latest image and restarted, and it's not working once I remove my custom CSS.

**Comment by Athou** [comment]
There's no release with this fix yet. It'll be part of 4.4.1 or something. I'll see if I have time to release it this weekend. In the meantime you can use the `master` tag on Docker Hub.

**Comment by Athou** [comment]
I just released 4.4.1 https://github.com/Athou/commafeed/releases/tag/4.4.1 !

**Comment by SConaway** [comment]
Thanks for releasing it. Unfortunately, I'm unable to scroll using the trackpad on my iPad, but the touchscreen works fine for it (and it's working fine on other platforms too). I might just go back to my custom CSS to reset `overscroll-behavior`.

**Comment by dos1** [comment]
This is also happening on WebKitGTK browsers, such as Epiphany. Still can't scroll in GNOME Web on my phone without custom CSS.

**Comment by Athou** [comment]
Since it seems to cause issues with different kind of browsers, I'm tempted to make it a setting instead of trying to guess what browsers support this.

@SConaway @dos1 what do you think?

**Comment by SConaway** [comment]
👍🏻 from me, happy to test on my platforms (if you can get me a docker image)

**Comment by Athou** [comment]
> 👍🏻 from me, happy to test on my platforms (if you can get me a docker image)

The setting is now available in the `master-<database>` docker image.

**Comment by Athou** [comment]
5.12.0 has been released with this new setting.

**Comment by SConaway** [comment]
Seems to work fine on my iPad!

**Comment by alexbartisro** [comment]
This still reproduces on Safari with https://www.commafeed.com

**Comment by Athou** [comment]
> This still reproduces on Safari with https://www.commafeed.com



Even with this setting disabled?

<img width="486" height="73" alt="Image" src="https://github.com/user-attachments/assets/5b6eda74-13f0-4d82-9588-757c00ba50fd" />

**Comment by alexbartisro** [comment]
@Athou that fixed it, thanks!
